package de.vitero.schema.sessioncode;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:26:22.360+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 *
 */
@WebService(targetNamespace = "http://www.vitero.de/schema/sessioncode", name = "SessionCode")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SessionCode {

    @WebMethod
    @WebResult(name = "getPersonalGroupSessionCodesResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "getPersonalGroupSessionCodesResponse")
    public GetPersonalGroupSessionCodesResponse getPersonalGroupSessionCodes(

        @WebParam(partName = "getPersonalGroupSessionCodesRequest", name = "getPersonalGroupSessionCodesRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        GetPersonalGroupSessionCodesRequest getPersonalGroupSessionCodesRequest
    );

    @WebMethod
    @WebResult(name = "getTestroomSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "getTestroomSessionCodeResponse")
    public Codetype getTestroomSessionCode(

        @WebParam(partName = "getTestroomSessionCodeRequest", name = "getTestroomSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        GetTestroomSessionCodeRequest getTestroomSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "successResponse")
    public SuccessResponse success(

        @WebParam(partName = "successRequest", name = "successRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        java.lang.String successRequest
    );

    @WebMethod
    @WebResult(name = "createAppointmentConfirmationSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createAppointmentConfirmationSessionCodeResponse")
    public Codetype createAppointmentConfirmationSessionCode(

        @WebParam(partName = "createAppointmentConfirmationSessionCodeRequest", name = "createAppointmentConfirmationSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreateAppointmentConfirmationSessionCodeRequest createAppointmentConfirmationSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "createGroupSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createGroupSessionCodeResponse")
    public Codetype createGroupSessionCode(

        @WebParam(partName = "createGroupSessionCodeRequest", name = "createGroupSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreateGroupSessionCodeRequest createGroupSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "createBookingSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createBookingSessionCodeResponse")
    public Codetype createBookingSessionCode(

        @WebParam(partName = "createBookingSessionCodeRequest", name = "createBookingSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreateBookingSessionCodeRequest createBookingSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "createPersonalGroupSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createPersonalGroupSessionCodeResponse")
    public Codetype createPersonalGroupSessionCode(

        @WebParam(partName = "createPersonalGroupSessionCodeRequest", name = "createPersonalGroupSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreatePersonalGroupSessionCodeRequest createPersonalGroupSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "createVmsSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createVmsSessionCodeResponse")
    public Codetype createVmsSessionCode(

        @WebParam(partName = "createVmsSessionCodeRequest", name = "createVmsSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreateVmsSessionCodeRequest createVmsSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "getPersonalBookingSessionCodesResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "getPersonalBookingSessionCodesResponse")
    public GetPersonalBookingSessionCodesResponse getPersonalBookingSessionCodes(

        @WebParam(partName = "getPersonalBookingSessionCodesRequest", name = "getPersonalBookingSessionCodesRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        GetPersonalBookingSessionCodesRequest getPersonalBookingSessionCodesRequest
    );

    @WebMethod
    @WebResult(name = "createWebaccessSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createWebaccessSessionCodeResponse")
    public CreateWebaccessSessionCodeResponse createWebaccessSessionCode(

        @WebParam(partName = "createWebaccessSessionCodeRequest", name = "createWebaccessSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreateWebaccessSessionCodeRequest createWebaccessSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "getSessionCodeInformationResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "getSessionCodeInformationResponse")
    public GetSessionCodeInformationResponse getSessionCodeInformation(

        @WebParam(partName = "getSessionCodeInformationRequest", name = "getSessionCodeInformationRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        GetSessionCodeInformationRequest getSessionCodeInformationRequest
    );

    @WebMethod
    @WebResult(name = "deleteSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "deleteSessionCodeResponse")
    public SuccessResponse deleteSessionCode(

        @WebParam(partName = "deleteSessionCodeRequest", name = "deleteSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        DeleteSessionCodeRequest deleteSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "createPersonalBookingSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createPersonalBookingSessionCodeResponse")
    public Codetype createPersonalBookingSessionCode(

        @WebParam(partName = "createPersonalBookingSessionCodeRequest", name = "createPersonalBookingSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreatePersonalBookingSessionCodeRequest createPersonalBookingSessionCodeRequest
    );
}
