package de.vitero.schema.sessioncode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-18T12:09:01.209+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://www.vitero.de/schema/sessioncode", name = "SessionCode")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@org.apache.cxf.annotations.EndpointProperty(key = "soap.no.validate.parts", value = "true")
public interface SessionCode {

    @WebMethod
    @WebResult(name = "getPersonalGroupSessionCodesResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "getPersonalGroupSessionCodesResponse")
    public GetPersonalGroupSessionCodesResponse getPersonalGroupSessionCodes(
        @WebParam(partName = "getPersonalGroupSessionCodesRequest", name = "getPersonalGroupSessionCodesRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        GetPersonalGroupSessionCodesRequest getPersonalGroupSessionCodesRequest
    );

    @WebMethod
    @WebResult(name = "getTestroomSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "getTestroomSessionCodeResponse")
    public Codetype getTestroomSessionCode(
        @WebParam(partName = "getTestroomSessionCodeRequest", name = "getTestroomSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        GetTestroomSessionCodeRequest getTestroomSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "successResponse")
    public SuccessResponse success(
        @WebParam(partName = "successRequest", name = "successRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        java.lang.String successRequest
    );

    @WebMethod
    @WebResult(name = "createAppointmentConfirmationSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createAppointmentConfirmationSessionCodeResponse")
    public Codetype createAppointmentConfirmationSessionCode(
        @WebParam(partName = "createAppointmentConfirmationSessionCodeRequest", name = "createAppointmentConfirmationSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreateAppointmentConfirmationSessionCodeRequest createAppointmentConfirmationSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "createGroupSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createGroupSessionCodeResponse")
    public Codetype createGroupSessionCode(
        @WebParam(partName = "createGroupSessionCodeRequest", name = "createGroupSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreateGroupSessionCodeRequest createGroupSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "createBookingSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createBookingSessionCodeResponse")
    public Codetype createBookingSessionCode(
        @WebParam(partName = "createBookingSessionCodeRequest", name = "createBookingSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreateBookingSessionCodeRequest createBookingSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "createPersonalGroupSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createPersonalGroupSessionCodeResponse")
    public Codetype createPersonalGroupSessionCode(
        @WebParam(partName = "createPersonalGroupSessionCodeRequest", name = "createPersonalGroupSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreatePersonalGroupSessionCodeRequest createPersonalGroupSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "createVmsSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createVmsSessionCodeResponse")
    public Codetype createVmsSessionCode(
        @WebParam(partName = "createVmsSessionCodeRequest", name = "createVmsSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreateVmsSessionCodeRequest createVmsSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "getPersonalBookingSessionCodesResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "getPersonalBookingSessionCodesResponse")
    public GetPersonalBookingSessionCodesResponse getPersonalBookingSessionCodes(
        @WebParam(partName = "getPersonalBookingSessionCodesRequest", name = "getPersonalBookingSessionCodesRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        GetPersonalBookingSessionCodesRequest getPersonalBookingSessionCodesRequest
    );

    @WebMethod
    @WebResult(name = "createWebaccessSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createWebaccessSessionCodeResponse")
    public CreateWebaccessSessionCodeResponse createWebaccessSessionCode(
        @WebParam(partName = "createWebaccessSessionCodeRequest", name = "createWebaccessSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreateWebaccessSessionCodeRequest createWebaccessSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "getSessionCodeInformationResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "getSessionCodeInformationResponse")
    public GetSessionCodeInformationResponse getSessionCodeInformation(
        @WebParam(partName = "getSessionCodeInformationRequest", name = "getSessionCodeInformationRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        GetSessionCodeInformationRequest getSessionCodeInformationRequest
    );

    @WebMethod
    @WebResult(name = "deleteSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "deleteSessionCodeResponse")
    public SuccessResponse deleteSessionCode(
        @WebParam(partName = "deleteSessionCodeRequest", name = "deleteSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        DeleteSessionCodeRequest deleteSessionCodeRequest
    );

    @WebMethod
    @WebResult(name = "createPersonalBookingSessionCodeResponse", targetNamespace = "http://www.vitero.de/schema/sessioncode", partName = "createPersonalBookingSessionCodeResponse")
    public Codetype createPersonalBookingSessionCode(
        @WebParam(partName = "createPersonalBookingSessionCodeRequest", name = "createPersonalBookingSessionCodeRequest", targetNamespace = "http://www.vitero.de/schema/sessioncode")
        CreatePersonalBookingSessionCodeRequest createPersonalBookingSessionCodeRequest
    );
}
