package de.vitero.schema.mtom;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:26:22.299+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 *
 */
@WebService(targetNamespace = "http://www.vitero.de/schema/mtom", name = "Mtom")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Mtom {

    @WebMethod
    @WebResult(name = "loadFileResponse", targetNamespace = "http://www.vitero.de/schema/mtom", partName = "loadFileResponse")
    public FileWrapper loadFile(

        @WebParam(partName = "loadFileRequest", name = "loadFileRequest", targetNamespace = "http://www.vitero.de/schema/mtom")
        IdWrapper loadFileRequest
    );

    @WebMethod
    @Oneway
    public void storeAvatar(

        @WebParam(partName = "storeAvatarRequest", name = "storeAvatarRequest", targetNamespace = "http://www.vitero.de/schema/mtom")
        CompleteAvatarWrapper storeAvatarRequest
    );

    @WebMethod
    @WebResult(name = "loadAvatarResponse", targetNamespace = "http://www.vitero.de/schema/mtom", partName = "loadAvatarResponse")
    public AvatarWrapper loadAvatar(

        @WebParam(partName = "loadAvatarRequest", name = "loadAvatarRequest", targetNamespace = "http://www.vitero.de/schema/mtom")
        AvatarInformation loadAvatarRequest
    );

    @WebMethod
    @WebResult(name = "storeFileResponse", targetNamespace = "http://www.vitero.de/schema/mtom", partName = "storeFileResponse")
    public IdWrapper storeFile(

        @WebParam(partName = "storeFileRequest", name = "storeFileRequest", targetNamespace = "http://www.vitero.de/schema/mtom")
        FileWrapper storeFileRequest
    );
}
