package de.vitero.schema.customer;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-15T21:49:26.907+02:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "CustomerService",
                  wsdlLocation = "classpath:wsdl/customer.wsdl",
                  targetNamespace = "http://www.vitero.de/schema/customer")
public class CustomerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.vitero.de/schema/customer", "CustomerService");
    public final static QName CustomerSoap11 = new QName("http://www.vitero.de/schema/customer", "CustomerSoap11");
    static {
        URL url = CustomerService.class.getClassLoader().getResource("wsdl/customer.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(CustomerService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/customer.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustomerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Customer
     */
    @WebEndpoint(name = "CustomerSoap11")
    public Customer getCustomerSoap11() {
        return super.getPort(CustomerSoap11, Customer.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Customer
     */
    @WebEndpoint(name = "CustomerSoap11")
    public Customer getCustomerSoap11(WebServiceFeature... features) {
        return super.getPort(CustomerSoap11, Customer.class, features);
    }

}
