package de.vitero.schema.customer;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-06T16:21:52.265+02:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://www.vitero.de/schema/customer", name = "Customer")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Customer {

    @WebResult(name = "getCustomerByNameResponse", targetNamespace = "http://www.vitero.de/schema/customer", partName = "getCustomerByNameResponse")
    @WebMethod
    public Customer_Type getCustomerByName(
        @WebParam(partName = "getCustomerByNameRequest", name = "getCustomerByNameRequest", targetNamespace = "http://www.vitero.de/schema/customer")
        GetCustomerByNameRequest getCustomerByNameRequest
    );

    @Oneway
    @WebMethod
    public void moveAllUsersToCustomer(
        @WebParam(partName = "moveAllUsersToCustomerRequest", name = "moveAllUsersToCustomerRequest", targetNamespace = "http://www.vitero.de/schema/customer")
        MoveAllUsersToCustomerRequest moveAllUsersToCustomerRequest
    );

    @Oneway
    @WebMethod
    public void addUserToCustomer(
        @WebParam(partName = "addUserToCustomerRequest", name = "addUserToCustomerRequest", targetNamespace = "http://www.vitero.de/schema/customer")
        Customeriduserid addUserToCustomerRequest
    );

    @WebResult(name = "getCustomerListResponse", targetNamespace = "http://www.vitero.de/schema/customer", partName = "getCustomerListResponse")
    @WebMethod
    public GetCustomerListResponse getCustomerList(
        @WebParam(partName = "getCustomerListRequest", name = "getCustomerListRequest", targetNamespace = "http://www.vitero.de/schema/customer")
        java.lang.Object getCustomerListRequest
    );

    @Oneway
    @WebMethod
    public void moveUserToCustomer(
        @WebParam(partName = "moveUserToCustomerRequest", name = "moveUserToCustomerRequest", targetNamespace = "http://www.vitero.de/schema/customer")
        MoveUserToCustomerRequest moveUserToCustomerRequest
    );

    @Oneway
    @WebMethod
    public void updateCustomer(
        @WebParam(partName = "updateCustomerRequest", name = "updateCustomerRequest", targetNamespace = "http://www.vitero.de/schema/customer")
        UpdateCustomerRequest updateCustomerRequest
    );

    @Oneway
    @WebMethod
    public void deleteCustomer(
        @WebParam(partName = "deleteCustomerRequest", name = "deleteCustomerRequest", targetNamespace = "http://www.vitero.de/schema/customer")
        Customerid deleteCustomerRequest
    );

    @WebResult(name = "getCustomerResponse", targetNamespace = "http://www.vitero.de/schema/customer", partName = "getCustomerResponse")
    @WebMethod
    public Customer_Type getCustomer(
        @WebParam(partName = "getCustomerRequest", name = "getCustomerRequest", targetNamespace = "http://www.vitero.de/schema/customer")
        Customerid getCustomerRequest
    );

    @Oneway
    @WebMethod
    public void removeUserFromCustomer(
        @WebParam(partName = "removeUserFromCustomerRequest", name = "removeUserFromCustomerRequest", targetNamespace = "http://www.vitero.de/schema/customer")
        Customeriduserid removeUserFromCustomerRequest
    );

    @WebResult(name = "createCustomerResponse", targetNamespace = "http://www.vitero.de/schema/customer", partName = "createCustomerResponse")
    @WebMethod
    public Customerid createCustomer(
        @WebParam(partName = "createCustomerRequest", name = "createCustomerRequest", targetNamespace = "http://www.vitero.de/schema/customer")
        CreateCustomerRequest createCustomerRequest
    );
}
