package de.vitero.schema.cms;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-08-23T08:45:10.667+02:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://www.vitero.de/schema/cms", name = "Cms")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Cms {

    @Oneway
    @WebMethod
    public void deleteNode(
        @WebParam(partName = "deleteNodeRequest", name = "deleteNodeRequest", targetNamespace = "http://www.vitero.de/schema/cms")
        Nodeid deleteNodeRequest
    );

    @Oneway
    @WebMethod
    public void changeDisplaytype(
        @WebParam(partName = "changeDisplaytypeRequest", name = "changeDisplaytypeRequest", targetNamespace = "http://www.vitero.de/schema/cms")
        ChangeDisplaytypeRequest changeDisplaytypeRequest
    );

    @Oneway
    @WebMethod
    public void renameNode(
        @WebParam(partName = "renameNodeRequest", name = "renameNodeRequest", targetNamespace = "http://www.vitero.de/schema/cms")
        RenameNodeRequest renameNodeRequest
    );

    @WebResult(name = "createFolderResponse", targetNamespace = "http://www.vitero.de/schema/cms", partName = "createFolderResponse")
    @WebMethod
    public Nodeid createFolder(
        @WebParam(partName = "createFolderRequest", name = "createFolderRequest", targetNamespace = "http://www.vitero.de/schema/cms")
        CreateFolderRequest createFolderRequest
    );

    @WebResult(name = "getGroupFolderResponse", targetNamespace = "http://www.vitero.de/schema/cms", partName = "getGroupFolderResponse")
    @WebMethod
    public WrappedFolder getGroupFolder(
        @WebParam(partName = "getGroupFolderRequest", name = "getGroupFolderRequest", targetNamespace = "http://www.vitero.de/schema/cms")
        GetGroupFolderRequest getGroupFolderRequest
    );

    @WebResult(name = "getCustomerFolderResponse", targetNamespace = "http://www.vitero.de/schema/cms", partName = "getCustomerFolderResponse")
    @WebMethod
    public WrappedFolder getCustomerFolder(
        @WebParam(partName = "getCustomerFolderRequest", name = "getCustomerFolderRequest", targetNamespace = "http://www.vitero.de/schema/cms")
        GetCustomerFolderRequest getCustomerFolderRequest
    );

    @Oneway
    @WebMethod
    public void copyNode(
        @WebParam(partName = "copyNodeRequest", name = "copyNodeRequest", targetNamespace = "http://www.vitero.de/schema/cms")
        SourceAndDestNodeId copyNodeRequest
    );

    @Oneway
    @WebMethod
    public void moveNode(
        @WebParam(partName = "moveNodeRequest", name = "moveNodeRequest", targetNamespace = "http://www.vitero.de/schema/cms")
        SourceAndDestNodeId moveNodeRequest
    );
}
