
package de.vitero.schema.cms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-08-23T08:45:10.650+02:00
 * Generated source version: 2.7.5
 * 
 */
public final class Cms_CmsSoap11_Client {

    private static final QName SERVICE_NAME = new QName("http://www.vitero.de/schema/cms", "CmsService");

    private Cms_CmsSoap11_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CmsService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CmsService ss = new CmsService(wsdlURL, SERVICE_NAME);
        Cms port = ss.getCmsSoap11();  
        
        {
        System.out.println("Invoking deleteNode...");
        de.vitero.schema.cms.Nodeid _deleteNode_deleteNodeRequest = null;
        port.deleteNode(_deleteNode_deleteNodeRequest);


        }
        {
        System.out.println("Invoking changeDisplaytype...");
        de.vitero.schema.cms.ChangeDisplaytypeRequest _changeDisplaytype_changeDisplaytypeRequest = null;
        port.changeDisplaytype(_changeDisplaytype_changeDisplaytypeRequest);


        }
        {
        System.out.println("Invoking renameNode...");
        de.vitero.schema.cms.RenameNodeRequest _renameNode_renameNodeRequest = null;
        port.renameNode(_renameNode_renameNodeRequest);


        }
        {
        System.out.println("Invoking createFolder...");
        de.vitero.schema.cms.CreateFolderRequest _createFolder_createFolderRequest = null;
        de.vitero.schema.cms.Nodeid _createFolder__return = port.createFolder(_createFolder_createFolderRequest);
        System.out.println("createFolder.result=" + _createFolder__return);


        }
        {
        System.out.println("Invoking getGroupFolder...");
        de.vitero.schema.cms.GetGroupFolderRequest _getGroupFolder_getGroupFolderRequest = null;
        de.vitero.schema.cms.WrappedFolder _getGroupFolder__return = port.getGroupFolder(_getGroupFolder_getGroupFolderRequest);
        System.out.println("getGroupFolder.result=" + _getGroupFolder__return);


        }
        {
        System.out.println("Invoking getCustomerFolder...");
        de.vitero.schema.cms.GetCustomerFolderRequest _getCustomerFolder_getCustomerFolderRequest = null;
        de.vitero.schema.cms.WrappedFolder _getCustomerFolder__return = port.getCustomerFolder(_getCustomerFolder_getCustomerFolderRequest);
        System.out.println("getCustomerFolder.result=" + _getCustomerFolder__return);


        }
        {
        System.out.println("Invoking copyNode...");
        de.vitero.schema.cms.SourceAndDestNodeId _copyNode_copyNodeRequest = null;
        port.copyNode(_copyNode_copyNodeRequest);


        }
        {
        System.out.println("Invoking moveNode...");
        de.vitero.schema.cms.SourceAndDestNodeId _moveNode_moveNodeRequest = null;
        port.moveNode(_moveNode_moveNodeRequest);


        }

        System.exit(0);
    }

}
