package de.vitero.schema.group;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-05-05T17:04:34.462+02:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://www.vitero.de/schema/group", name = "Group")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@org.apache.cxf.annotations.EndpointProperty(key = "soap.no.validate.parts", value = "true")
public interface Group {

    @WebMethod
    @WebResult(name = "isUserInGroupResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "isUserInGroupResponse")
    public IsUserInGroupResponse isUserInGroup(

        @WebParam(partName = "isUserInGroupRequest", name = "isUserInGroupRequest", targetNamespace = "http://www.vitero.de/schema/group")
        Groupiduserid isUserInGroupRequest
    );

    @WebMethod
    @WebResult(name = "successResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "successResponse")
    public SuccessResponse success(

        @WebParam(partName = "successRequest", name = "successRequest", targetNamespace = "http://www.vitero.de/schema/group")
        java.lang.String successRequest
    );

    @WebMethod
    @WebResult(name = "getGroupResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "getGroupResponse")
    public Group_Type getGroup(

        @WebParam(partName = "getGroupRequest", name = "getGroupRequest", targetNamespace = "http://www.vitero.de/schema/group")
        Groupid getGroupRequest
    );

    @WebMethod
    @WebResult(name = "getGroupListByCustomerResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "getGroupListByCustomerResponse")
    public GetGroupListByCustomerResponse getGroupListByCustomer(

        @WebParam(partName = "getGroupListByCustomerRequest", name = "getGroupListByCustomerRequest", targetNamespace = "http://www.vitero.de/schema/group")
        GetGroupListByCustomerRequest getGroupListByCustomerRequest
    );

    @WebMethod
    @WebResult(name = "addUserToGroupResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "addUserToGroupResponse")
    public SuccessResponse addUserToGroup(

        @WebParam(partName = "addUserToGroupRequest", name = "addUserToGroupRequest", targetNamespace = "http://www.vitero.de/schema/group")
        Groupiduseridstrict addUserToGroupRequest
    );

    @WebMethod
    @WebResult(name = "deleteGroupResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "deleteGroupResponse")
    public SuccessResponse deleteGroup(

        @WebParam(partName = "deleteGroupRequest", name = "deleteGroupRequest", targetNamespace = "http://www.vitero.de/schema/group")
        DeleteGroupRequest deleteGroupRequest
    );

    @WebMethod
    @WebResult(name = "changeGroupRoleResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "changeGroupRoleResponse")
    public SuccessResponse changeGroupRole(

        @WebParam(partName = "changeGroupRoleRequest", name = "changeGroupRoleRequest", targetNamespace = "http://www.vitero.de/schema/group")
        ChangeGroupRoleRequest changeGroupRoleRequest
    );

    @WebMethod
    @WebResult(name = "createGroupResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "createGroupResponse")
    public Groupid createGroup(

        @WebParam(partName = "createGroupRequest", name = "createGroupRequest", targetNamespace = "http://www.vitero.de/schema/group")
        CreateGroupRequest createGroupRequest
    );

    @WebMethod
    @WebResult(name = "changeEnabledResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "changeEnabledResponse")
    public SuccessResponse changeEnabled(

        @WebParam(partName = "changeEnabledRequest", name = "changeEnabledRequest", targetNamespace = "http://www.vitero.de/schema/group")
        ChangeEnabledRequest changeEnabledRequest
    );

    @WebMethod
    @WebResult(name = "getGroupByNameResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "getGroupByNameResponse")
    public Group_Type getGroupByName(

        @WebParam(partName = "getGroupByNameRequest", name = "getGroupByNameRequest", targetNamespace = "http://www.vitero.de/schema/group")
        Groupnamecustomerid getGroupByNameRequest
    );

    @WebMethod
    @WebResult(name = "updateGroupResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "updateGroupResponse")
    public SuccessResponse updateGroup(

        @WebParam(partName = "updateGroupRequest", name = "updateGroupRequest", targetNamespace = "http://www.vitero.de/schema/group")
        UpdateGroupRequest updateGroupRequest
    );

    @WebMethod
    @WebResult(name = "getParticipantResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "getParticipantResponse")
    public GetParticipantResponse getParticipant(

        @WebParam(partName = "getParticipantRequest", name = "getParticipantRequest", targetNamespace = "http://www.vitero.de/schema/group")
        Groupiduserid getParticipantRequest
    );

    @WebMethod
    @WebResult(name = "removeUserFromGroupResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "removeUserFromGroupResponse")
    public SuccessResponse removeUserFromGroup(

        @WebParam(partName = "removeUserFromGroupRequest", name = "removeUserFromGroupRequest", targetNamespace = "http://www.vitero.de/schema/group")
        Groupiduseridstrict removeUserFromGroupRequest
    );
}
