package de.vitero.schema.group;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-06T16:21:52.465+02:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://www.vitero.de/schema/group", name = "Group")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Group {

    @WebResult(name = "getGroupByNameResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "getGroupByNameResponse")
    @WebMethod
    public Group_Type getGroupByName(
        @WebParam(partName = "getGroupByNameRequest", name = "getGroupByNameRequest", targetNamespace = "http://www.vitero.de/schema/group")
        Groupnamecustomerid getGroupByNameRequest
    );

    @Oneway
    @WebMethod
    public void addUserToGroup(
        @WebParam(partName = "addUserToGroupRequest", name = "addUserToGroupRequest", targetNamespace = "http://www.vitero.de/schema/group")
        Groupiduserid addUserToGroupRequest
    );

    @WebResult(name = "getGroupListByCustomerResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "getGroupListByCustomerResponse")
    @WebMethod
    public GetGroupListByCustomerResponse getGroupListByCustomer(
        @WebParam(partName = "getGroupListByCustomerRequest", name = "getGroupListByCustomerRequest", targetNamespace = "http://www.vitero.de/schema/group")
        GetGroupListByCustomerRequest getGroupListByCustomerRequest
    );

    @Oneway
    @WebMethod
    public void changeGroupRole(
        @WebParam(partName = "changeGroupRoleRequest", name = "changeGroupRoleRequest", targetNamespace = "http://www.vitero.de/schema/group")
        ChangeGroupRoleRequest changeGroupRoleRequest
    );

    @Oneway
    @WebMethod
    public void removeUserFromGroup(
        @WebParam(partName = "removeUserFromGroupRequest", name = "removeUserFromGroupRequest", targetNamespace = "http://www.vitero.de/schema/group")
        Groupiduserid removeUserFromGroupRequest
    );

    @WebResult(name = "getGroupResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "getGroupResponse")
    @WebMethod
    public Group_Type getGroup(
        @WebParam(partName = "getGroupRequest", name = "getGroupRequest", targetNamespace = "http://www.vitero.de/schema/group")
        Groupid getGroupRequest
    );

    @Oneway
    @WebMethod
    public void changeEnabled(
        @WebParam(partName = "changeEnabledRequest", name = "changeEnabledRequest", targetNamespace = "http://www.vitero.de/schema/group")
        ChangeEnabledRequest changeEnabledRequest
    );

    @WebResult(name = "createGroupResponse", targetNamespace = "http://www.vitero.de/schema/group", partName = "createGroupResponse")
    @WebMethod
    public Groupid createGroup(
        @WebParam(partName = "createGroupRequest", name = "createGroupRequest", targetNamespace = "http://www.vitero.de/schema/group")
        CreateGroupRequest createGroupRequest
    );

    @Oneway
    @WebMethod
    public void updateGroup(
        @WebParam(partName = "updateGroupRequest", name = "updateGroupRequest", targetNamespace = "http://www.vitero.de/schema/group")
        UpdateGroupRequest updateGroupRequest
    );

    @Oneway
    @WebMethod
    public void deleteGroup(
        @WebParam(partName = "deleteGroupRequest", name = "deleteGroupRequest", targetNamespace = "http://www.vitero.de/schema/group")
        Groupid deleteGroupRequest
    );
}
