
package de.vitero.schema.group;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-18T12:09:00.985+01:00
 * Generated source version: 3.2.7
 *
 */
public final class Group_GroupSoap11_Client {

    private static final QName SERVICE_NAME = new QName("http://www.vitero.de/schema/group", "GroupService");

    private Group_GroupSoap11_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GroupService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GroupService ss = new GroupService(wsdlURL, SERVICE_NAME);
        Group port = ss.getGroupSoap11();

        {
        System.out.println("Invoking isUserInGroup...");
        de.vitero.schema.group.Groupiduserid _isUserInGroup_isUserInGroupRequest = null;
        de.vitero.schema.group.IsUserInGroupResponse _isUserInGroup__return = port.isUserInGroup(_isUserInGroup_isUserInGroupRequest);
        System.out.println("isUserInGroup.result=" + _isUserInGroup__return);


        }
        {
        System.out.println("Invoking success...");
        java.lang.String _success_successRequest = "";
        de.vitero.schema.group.SuccessResponse _success__return = port.success(_success_successRequest);
        System.out.println("success.result=" + _success__return);


        }
        {
        System.out.println("Invoking getGroup...");
        de.vitero.schema.group.Groupid _getGroup_getGroupRequest = null;
        de.vitero.schema.group.Group_Type _getGroup__return = port.getGroup(_getGroup_getGroupRequest);
        System.out.println("getGroup.result=" + _getGroup__return);


        }
        {
        System.out.println("Invoking getGroupListByCustomer...");
        de.vitero.schema.group.GetGroupListByCustomerRequest _getGroupListByCustomer_getGroupListByCustomerRequest = null;
        de.vitero.schema.group.GetGroupListByCustomerResponse _getGroupListByCustomer__return = port.getGroupListByCustomer(_getGroupListByCustomer_getGroupListByCustomerRequest);
        System.out.println("getGroupListByCustomer.result=" + _getGroupListByCustomer__return);


        }
        {
        System.out.println("Invoking addUserToGroup...");
        de.vitero.schema.group.Groupiduseridstrict _addUserToGroup_addUserToGroupRequest = null;
        de.vitero.schema.group.SuccessResponse _addUserToGroup__return = port.addUserToGroup(_addUserToGroup_addUserToGroupRequest);
        System.out.println("addUserToGroup.result=" + _addUserToGroup__return);


        }
        {
        System.out.println("Invoking deleteGroup...");
        de.vitero.schema.group.DeleteGroupRequest _deleteGroup_deleteGroupRequest = null;
        de.vitero.schema.group.SuccessResponse _deleteGroup__return = port.deleteGroup(_deleteGroup_deleteGroupRequest);
        System.out.println("deleteGroup.result=" + _deleteGroup__return);


        }
        {
        System.out.println("Invoking changeGroupRole...");
        de.vitero.schema.group.ChangeGroupRoleRequest _changeGroupRole_changeGroupRoleRequest = null;
        de.vitero.schema.group.SuccessResponse _changeGroupRole__return = port.changeGroupRole(_changeGroupRole_changeGroupRoleRequest);
        System.out.println("changeGroupRole.result=" + _changeGroupRole__return);


        }
        {
        System.out.println("Invoking createGroup...");
        de.vitero.schema.group.CreateGroupRequest _createGroup_createGroupRequest = null;
        de.vitero.schema.group.Groupid _createGroup__return = port.createGroup(_createGroup_createGroupRequest);
        System.out.println("createGroup.result=" + _createGroup__return);


        }
        {
        System.out.println("Invoking changeEnabled...");
        de.vitero.schema.group.ChangeEnabledRequest _changeEnabled_changeEnabledRequest = null;
        de.vitero.schema.group.SuccessResponse _changeEnabled__return = port.changeEnabled(_changeEnabled_changeEnabledRequest);
        System.out.println("changeEnabled.result=" + _changeEnabled__return);


        }
        {
        System.out.println("Invoking getGroupByName...");
        de.vitero.schema.group.Groupnamecustomerid _getGroupByName_getGroupByNameRequest = null;
        de.vitero.schema.group.Group_Type _getGroupByName__return = port.getGroupByName(_getGroupByName_getGroupByNameRequest);
        System.out.println("getGroupByName.result=" + _getGroupByName__return);


        }
        {
        System.out.println("Invoking updateGroup...");
        de.vitero.schema.group.UpdateGroupRequest _updateGroup_updateGroupRequest = null;
        de.vitero.schema.group.SuccessResponse _updateGroup__return = port.updateGroup(_updateGroup_updateGroupRequest);
        System.out.println("updateGroup.result=" + _updateGroup__return);


        }
        {
        System.out.println("Invoking getParticipant...");
        de.vitero.schema.group.Groupiduserid _getParticipant_getParticipantRequest = null;
        de.vitero.schema.group.GetParticipantResponse _getParticipant__return = port.getParticipant(_getParticipant_getParticipantRequest);
        System.out.println("getParticipant.result=" + _getParticipant__return);


        }
        {
        System.out.println("Invoking removeUserFromGroup...");
        de.vitero.schema.group.Groupiduseridstrict _removeUserFromGroup_removeUserFromGroupRequest = null;
        de.vitero.schema.group.SuccessResponse _removeUserFromGroup__return = port.removeUserFromGroup(_removeUserFromGroup_removeUserFromGroupRequest);
        System.out.println("removeUserFromGroup.result=" + _removeUserFromGroup__return);


        }

        System.exit(0);
    }

}
