package de.vitero.schema.booking;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-08-23T08:45:10.460+02:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://www.vitero.de/schema/booking", name = "Booking")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Booking {

    @Oneway
    @WebMethod
    public void updateBooking(
        @WebParam(partName = "updateBookingRequest", name = "updateBookingRequest", targetNamespace = "http://www.vitero.de/schema/booking")
        UpdateBookingRequest updateBookingRequest
    );

    @WebResult(name = "getBookingListByUserAndDateResponse", targetNamespace = "http://www.vitero.de/schema/booking", partName = "getBookingListByUserAndDateResponse")
    @WebMethod
    public Bookinglist getBookingListByUserAndDate(
        @WebParam(partName = "getBookingListByUserAndDateRequest", name = "getBookingListByUserAndDateRequest", targetNamespace = "http://www.vitero.de/schema/booking")
        GetBookingListByUserAndDateRequest getBookingListByUserAndDateRequest
    );

    @WebResult(name = "getBookingListByDateResponse", targetNamespace = "http://www.vitero.de/schema/booking", partName = "getBookingListByDateResponse")
    @WebMethod
    public Bookinglist getBookingListByDate(
        @WebParam(partName = "getBookingListByDateRequest", name = "getBookingListByDateRequest", targetNamespace = "http://www.vitero.de/schema/booking")
        GetBookingListByDateRequest getBookingListByDateRequest
    );

    @WebResult(name = "getBookingListByUserInFutureResponse", targetNamespace = "http://www.vitero.de/schema/booking", partName = "getBookingListByUserInFutureResponse")
    @WebMethod
    public Bookinglist getBookingListByUserInFuture(
        @WebParam(partName = "getBookingListByUserInFutureRequest", name = "getBookingListByUserInFutureRequest", targetNamespace = "http://www.vitero.de/schema/booking")
        GetBookingListByUserInFutureRequest getBookingListByUserInFutureRequest
    );

    @WebResult(name = "getBookingListByGroupInFutureResponse", targetNamespace = "http://www.vitero.de/schema/booking", partName = "getBookingListByGroupInFutureResponse")
    @WebMethod
    public Bookinglist getBookingListByGroupInFuture(
        @WebParam(partName = "getBookingListByGroupInFutureRequest", name = "getBookingListByGroupInFutureRequest", targetNamespace = "http://www.vitero.de/schema/booking")
        GetBookingListByGroupInFutureRequest getBookingListByGroupInFutureRequest
    );

    @WebResult(name = "createBookingResponse", targetNamespace = "http://www.vitero.de/schema/booking", partName = "createBookingResponse")
    @WebMethod
    public CreateBookingResponse createBooking(
        @WebParam(partName = "createBookingRequest", name = "createBookingRequest", targetNamespace = "http://www.vitero.de/schema/booking")
        CreateBookingRequest createBookingRequest
    );

    @WebResult(name = "getBookingTimeByIdResponse", targetNamespace = "http://www.vitero.de/schema/booking", partName = "getBookingTimeByIdResponse")
    @WebMethod
    public Bookingtimetype getBookingTimeById(
        @WebParam(partName = "getBookingTimeByIdRequest", name = "getBookingTimeByIdRequest", targetNamespace = "http://www.vitero.de/schema/booking")
        Bookingtimeid getBookingTimeByIdRequest
    );

    @WebResult(name = "getBookingByIdResponse", targetNamespace = "http://www.vitero.de/schema/booking", partName = "getBookingByIdResponse")
    @WebMethod
    public Bookingtype getBookingById(
        @WebParam(partName = "getBookingByIdRequest", name = "getBookingByIdRequest", targetNamespace = "http://www.vitero.de/schema/booking")
        Bookingid getBookingByIdRequest
    );

    @WebResult(name = "getBookingListByGroupAndDateResponse", targetNamespace = "http://www.vitero.de/schema/booking", partName = "getBookingListByGroupAndDateResponse")
    @WebMethod
    public Bookinglist getBookingListByGroupAndDate(
        @WebParam(partName = "getBookingListByGroupAndDateRequest", name = "getBookingListByGroupAndDateRequest", targetNamespace = "http://www.vitero.de/schema/booking")
        GetBookingListByGroupAndDateRequest getBookingListByGroupAndDateRequest
    );

    @WebResult(name = "deleteBookingResponse", targetNamespace = "http://www.vitero.de/schema/booking", partName = "deleteBookingResponse")
    @WebMethod
    public DeleteBookingResponse deleteBooking(
        @WebParam(partName = "deleteBookingRequest", name = "deleteBookingRequest", targetNamespace = "http://www.vitero.de/schema/booking")
        DeleteBookingRequest deleteBookingRequest
    );

    @WebResult(name = "getBookingByBookingTimeIdResponse", targetNamespace = "http://www.vitero.de/schema/booking", partName = "getBookingByBookingTimeIdResponse")
    @WebMethod
    public Bookingtype getBookingByBookingTimeId(
        @WebParam(partName = "getBookingByBookingTimeIdRequest", name = "getBookingByBookingTimeIdRequest", targetNamespace = "http://www.vitero.de/schema/booking")
        Bookingtimeid getBookingByBookingTimeIdRequest
    );
}
