package de.vitero.schema.booking;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-654444433f3b17123cbc00fd17ea1c10d7de7a9c
 * 2022-10-18T10:04:13.694+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 *
 */
@WebServiceClient(name = "BookingService",
                  wsdlLocation = "classpath:wsdl/booking.wsdl",
                  targetNamespace = "http://www.vitero.de/schema/booking")
public class BookingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.vitero.de/schema/booking", "BookingService");
    public final static QName BookingSoap11 = new QName("http://www.vitero.de/schema/booking", "BookingSoap11");
    static {
        URL url = BookingService.class.getClassLoader().getResource("wsdl/booking.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(BookingService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/booking.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BookingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BookingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookingService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BookingService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BookingService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BookingService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Booking
     */
    @WebEndpoint(name = "BookingSoap11")
    public Booking getBookingSoap11() {
        return super.getPort(BookingSoap11, Booking.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Booking
     */
    @WebEndpoint(name = "BookingSoap11")
    public Booking getBookingSoap11(WebServiceFeature... features) {
        return super.getPort(BookingSoap11, Booking.class, features);
    }

}
