package de.vitero.schema.user;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-06T16:09:03.703+02:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://www.vitero.de/schema/user", name = "User")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface User {

    @Oneway
    @WebMethod
    public void deleteUser(
        @WebParam(partName = "deleteUserRequest", name = "deleteUserRequest", targetNamespace = "http://www.vitero.de/schema/user")
        Userid deleteUserRequest
    );

    @Oneway
    @WebMethod
    public void updateUser(
        @WebParam(partName = "updateUserRequest", name = "updateUserRequest", targetNamespace = "http://www.vitero.de/schema/user")
        UpdateUserRequest updateUserRequest
    );

    @WebResult(name = "getUserListByGroupResponse", targetNamespace = "http://www.vitero.de/schema/user", partName = "getUserListByGroupResponse")
    @WebMethod
    public Userlist getUserListByGroup(
        @WebParam(partName = "getUserListByGroupRequest", name = "getUserListByGroupRequest", targetNamespace = "http://www.vitero.de/schema/user")
        GetUserListByGroupRequest getUserListByGroupRequest
    );

    @WebResult(name = "getUserListResponse", targetNamespace = "http://www.vitero.de/schema/user", partName = "getUserListResponse")
    @WebMethod
    public Userlist getUserList(
        @WebParam(partName = "getUserListRequest", name = "getUserListRequest", targetNamespace = "http://www.vitero.de/schema/user")
        java.lang.Object getUserListRequest
    );

    @WebResult(name = "getUserListByCustomerResponse", targetNamespace = "http://www.vitero.de/schema/user", partName = "getUserListByCustomerResponse")
    @WebMethod
    public Userlist getUserListByCustomer(
        @WebParam(partName = "getUserListByCustomerRequest", name = "getUserListByCustomerRequest", targetNamespace = "http://www.vitero.de/schema/user")
        GetUserListByCustomerRequest getUserListByCustomerRequest
    );

    @WebResult(name = "getUserResponse", targetNamespace = "http://www.vitero.de/schema/user", partName = "getUserResponse")
    @WebMethod
    public GetUserResponse getUser(
        @WebParam(partName = "getUserRequest", name = "getUserRequest", targetNamespace = "http://www.vitero.de/schema/user")
        Userid getUserRequest
    );

    @WebResult(name = "getUserCountResponse", targetNamespace = "http://www.vitero.de/schema/user", partName = "getUserCountResponse")
    @WebMethod
    public GetUserCountResponse getUserCount(
        @WebParam(partName = "getUserCountRequest", name = "getUserCountRequest", targetNamespace = "http://www.vitero.de/schema/user")
        GetUserCountRequest getUserCountRequest
    );

    @WebResult(name = "getUserListByPositionResponse", targetNamespace = "http://www.vitero.de/schema/user", partName = "getUserListByPositionResponse")
    @WebMethod
    public Userlist getUserListByPosition(
        @WebParam(partName = "getUserListByPositionRequest", name = "getUserListByPositionRequest", targetNamespace = "http://www.vitero.de/schema/user")
        GetUserListByPositionRequest getUserListByPositionRequest
    );

    @Oneway
    @WebMethod
    public void changePassword(
        @WebParam(partName = "changePasswordRequest", name = "changePasswordRequest", targetNamespace = "http://www.vitero.de/schema/user")
        ChangePasswordRequest changePasswordRequest
    );

    @WebResult(name = "createUserResponse", targetNamespace = "http://www.vitero.de/schema/user", partName = "createUserResponse")
    @WebMethod
    public Userid createUser(
        @WebParam(partName = "createUserRequest", name = "createUserRequest", targetNamespace = "http://www.vitero.de/schema/user")
        CreateUserRequest createUserRequest
    );
}
