package de.vitero;



/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.handler.Handler;
import javax.xml.ws.handler.HandlerResolver;
import javax.xml.ws.handler.PortInfo;

import de.vitero.schema.licence.GetModulesForCustomerRequest;
import de.vitero.schema.licence.Licence;
import de.vitero.schema.licence.LicenceService;
import de.vitero.schema.licence.Modulestype;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-04T20:25:23.779+02:00
 * Generated source version: 2.7.5
 * 
 * Simple example to connect to vitero
 * 
 */
public final class Licence_Client {

    private static final QName SERVICE_NAME = new QName("http://www.vitero.de/schema/licence", "LicenceService");

    private Licence_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LicenceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LicenceService ss = new LicenceService(wsdlURL, SERVICE_NAME);
        ss.setHandlerResolver(new HandlerResolver() {
					@SuppressWarnings("rawtypes")
					@Override
					public List<Handler> getHandlerChain(PortInfo portInfo) {
						List<Handler> handlerList = new ArrayList<Handler>();
						//handlerList.add(new ViteroSecurityHandler("admin", "007"));
						return handlerList;
					}
        	
        });
        Licence port = ss.getLicenceSoap11();

        String url = "http://localhost:8095/vitero/services/LicenseService";
        ((BindingProvider)port).getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, url);

        System.out.println("Invoking getModulesForCustomer...");
        GetModulesForCustomerRequest request = new GetModulesForCustomerRequest();
        request.setCustomerid(1);
        Modulestype type = port.getModulesForCustomer(request);
        System.out.println("getModulesForCustomer.result=" + type);

        System.exit(0);
    }
}
